const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Adidas",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Reebok Slim Shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Reebok",
      rating: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Fila Slim Shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Fila",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Asics Slim Shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Asics",
      rating: 4.6,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Puma Slim Shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
